const projectList = [
{
  "title": "NYCHA Outage Scraper",
  "imageurl": "https://i.imgur.com/3CmQKwE.png",
  "statement": "The New York City Housing Authority (NYCHA) maintains a page on their site that lists services outages in thier developments for heat, hot water, water, elevators, electricity & gas. \n The outage site is updated regularly, however there is no easy way for stakeholders to download the data. This scraper extracts the data from the NYCHA website and saves the results in csv tables, within a folder named with the date and time of the scrape.",
  "techused": "Python/Beautiful Soup/Pandas",
  "url": "https://github.com/snphillips/nycha-outage-scraper",
  "githuburl": "https://github.com/snphillips/nycha-outage-scraper",
  "year": "2020",
  "includeingallery": true,
},
{
  "title": "Artist Portfolio",
  "imageurl": "https://i.imgur.com/pP8Ne6d.png",
  "statement": "A portfolio website for my visual art. \r The site includes a gallery and image modals.",
  "techused": "React",
  "url": "https://sarahnicolephillipsart.surge.sh/",
  "githuburl": "https://github.com/snphillips/artportfolio",
  "year": "2020",
  "includeingallery": true,
},
{
  "title": "No Frillz Tweets",
  "imageurl": "https://i.imgur.com/dofkpVD.png",
  "statement": "no frillz twitter is a simple twitter client that returns recent tweets based on the user's search query.",
  "techused": "Node/Express/Javascript/Twit API",
  "url": "https://nofrillztweets.surge.sh/",
  "githuburl": "https://github.com/snphillips/nofrillztwitter",
  "year": "2020",
  "includeingallery": true,
},
{
  "title": "About a Blue Bike",
  "imageurl": "https://i.imgur.com/A1J5MxP.jpg",
  "statement": "About a Blue Bike is a tool to look up trip statistics about individual bicycles in New York City's Citi Bike bike share system.",
  "techused": "Node/Express/Postgres/React",
  "url": "https://aboutabluebike.surge.sh/",
  "githuburl": "https://github.com/snphillips/About-a-Blue-Bike",
  "year": "2018",
  "includeingallery": false,
},
{
  "title": "So Trashy",
  "imageurl":  "https://i.imgur.com/Zf8LOkR.png",
  "statement": "So Trashy uses data visualization to represent New York City's Department of Sanitation's yearly collection of refuse & recycling.",
  "techused": "D3.js/React.js/nyc.gov APIs",
  "url": "https://so-trashy-react.surge.sh/",
  "githuburl": "https://github.com/snphillips/So-Trashy-React",
  "year": "2018",
  "includeingallery": true,
},
{
  "title": "Art Thief",
  "imageurl": "https://i.imgur.com/CKtB3Sl.png",
  "statement": "Art Thief allows users to view random imageurls from the Cooper Hewitt Museum's collection, based on selected keywords such as angular, art deco, modernism etc.",
  "techused": "Node/Express/React/Cooper Hewitt Museum API",
  "url": "https://art-thief.surge.sh/",
  "githuburl": "https://github.com/snphillips/art-thief",
  "year": "2018",
  "includeingallery": true,
},
{
  "title": "TwoHue",
  "imageurl": "https://i.imgur.com/i91exEK.png",
  "statement": "Twohue is a one-player color mixing game. Players are presented with a color sample that they must recreate using two transparent color swatches. I use a state-machine to manage user flow.",
  "techused": "React/React-Automata (for state machine)/Chroma.js",
  "url": "https://twohue-state-machine.surge.sh/",
  "githuburl": "https://github.com/snphillips/twohue-state-chart",
  "year": "2020",
  "includeingallery": true,
},
{
  "title": "Weather GIF",
  "imageurl": "https://i.imgur.com/ruPKEqn.png",
  "statement": "WeatherGIF is a silly little weather app that displays current weather conditions based on ZIP, accompanied by an animated GIF that illustrates the weather.",
  "techused": "Javascript/Open Weather API",
  "url": "https://weathergif.surge.sh/",
  "githuburl": "https://github.com/snphillips/weatherGIF",
  "year": "2018",
  "includeingallery": true,
},
{
  "title": "Five Years of Food Spending",
  "imageurl": "https://i.imgur.com/pXdIzAO.png",
  "statement": "Five Years of Food Spending uses data visualization to represent my spending on groceries and eating out.",
  "techused": "D3.js/React.js",
  "url": "https://5yearsfood.surge.sh/",
  "githuburl": "https://github.com/snphillips/food-spending",
  "year": "2018",
  "includeingallery": true,
},
{
  "title": "Todoodles",
  "imageurl": "https://i.imgur.com/DNmSSeE.png",
  "statement": "Todoodles is a CRUD TODO app that allows users to create & delete todo items, as well as cross out completed tasks.",
  "techused": "Node/Express/React/Postgres",
  "url": "https://todoodles.surge.sh/",
  "githuburl": "https://github.com/snphillips/todoodles",
  "year": "2018",
  "includeingallery": false,
}
]

export default projectList
